# Generated by Django 4.1.2 on 2022-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_file_name_file_file_size_file_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
